export const RESTAURANT_CATEGORIES = [
  { key: "KOREAN", value: "한식" },
  { key: "JAPANESE", value: "일식" },
  { key: "CHINESE", value: "중식" },
  { key: "WESTERN", value: "양식" },
  { key: "CAFE", value: "카페" },
  { key: "PUB", value: "술집" },
  { key: "FASTFOOD", value: "패스트푸드" },
  { key: "CHICKEN", value: "치킨" },
  { key: "BUNSIK", value: "분식" },
  { key: "SHABU", value: "샤브샤브" },
  { key: "SNACK", value: "간식" },
  { key: "ASIAN", value: "아시아음식" },
  { key: "SALAD", value: "샐러드" },
  { key: "LUNCH_BOX", value: "도시락" },
  { key: "OTHER", value: "기타" },
] as const;
